# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  env:
    SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    CONNECTIONSERVICENAME: ${{ secrets.CONNECTIONSERVICENAME }}
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $CONNECTIONSERVICENAME
    subscriptionId: $SUBSCRIPTION_ID
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'apim-ci-cd-arm-validate'
    location: 'Japan East'
    templateLocation: 'Linked artifact'
    csmFile: 'instance.json'
    csmParametersFile: 'parameter.json'
    deploymentMode: 'Validation'

- task: Delete Resource Group if it is empty@1
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: $CONNECTIONSERVICENAME
    resourceGroupName: 'apim-ci-cd-arm-validate'

- task: CopyFiles@2
  inputs:
    Contents: '*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ValidatedArtifact'
    publishLocation: 'Container'
