name: Run Azure Login with OpenID Connect via Azure CLI
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Login-Azure-on-Linux:
    runs-on: ubuntu-latest
    steps:
    - name: OIDC Login to Azure Public Cloud with Azure CLI
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
